- platform: workday
  name: Workday
  country: SE
- platform: apcupsd
- platform: template
  sensors:
    people_home:
     friendly_name: 'People Home'
     device_class: presence
     value_template: >
       {{ is_state('person.person1', 'home') or
          is_state('person.person2', 'home') }}
