- platform: workday
  name: Workday
  country: SE
- platform: apcupsd
- platform: template
  sensors:
    people_home:
     friendly_name: 'People Home'
     device_class: presence
     value_template: >
       {{ is_state('person.person1', 'home') or
          is_state('person.person2', 'home') }}
- platform: ping
  host: 8.8.8.8
  count: 2
  scan_interval: 60
  name: Internet Connection
- platform: tod
  name: Kids Bedtime
  after: '18:00'
  before: '22:00'
- platform: tod
  name: Parents Bedtime
  after: '21:00'
  before: '00:00'
