homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  unit_system: metric
  time_zone: !secret time_zone_home
  elevation: !secret elevation_home
  temperature_unit: C
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 10.0.0.0/24
  auth_mfa_modules:
    - type: totp
  customize: !include customize.yaml
  external_url: !secret external_url
  internal_url: !secret internal_url

lovelace:
  mode: yaml
  resources:
    - url: /local/mini-graph-card-bundle.js
      type: module
  dashboards:
    lovelace-tech:
      mode: yaml
      filename: dashboard-tech.yaml
      title: Teknik
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: false
    lovelace-alarm:
      mode: yaml
      filename: dashboard-alarm.yaml
      title: Larm
      icon: mdi:home-lock
      show_in_sidebar: true
      require_admin: true

config:

sun:

frontend:

mobile_app:

http:
  use_x_forwarded_for: True
  trusted_proxies:
    - 10.0.0.8
    - 127.0.0.1

tts:
  - platform: google_translate
    service_name: google_say

ssdp:

discovery:

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 90

history:

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

group: !include_dir_merge_named groups
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switches.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include binary_sensors.yaml
zone: !secret zones
person: !secret persons
knx: !include knx.yaml
input_text: !include input_text.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
timer: !include timers.yaml
counter: !include counters.yaml

notify:
  - name: Pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: All Apps
    platform: group
    services:
      - service: mobile_app_sm_g970f
      - service: mobile_app_sofhias_iphone

verisure:
  username: !secret verisure_username
  password: !secret verisure_password
  hygrometers: false
  smartplugs: false
  thermometers: false
  mouse: false
  door_window: false
  locks: false

map:

tellstick:
  host: localhost
  port: [50800, 50801]
  signal_repetitions: 2

webostv:
  host: livingroom-tv.home
  name: Livingroom TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret livingroom_tv_mac_address

wake_on_lan:

asuswrt:
  host: wireless-ap.home
  username: admin
  ssh_key: /config/id_rsa
  sensors:
    - upload
    - download
    - upload_speed
    - download_speed

device_tracker:
  - platform: asuswrt
    host: wireless-ap.home
    username: admin
    ssh_key: /config/id_rsa
    protocol: ssh
    interval_seconds: 10
    consider_home: 30
    new_device_defaults:
      track_new_devices: true
  - platform: mqtt
    devices:
      person1_smart_band_basement: 'monitor/basement/DD:69:66:E7:0F:DD/device_tracker'
      person1_smart_band_ground_floor: 'monitor/ground_floor/DD:69:66:E7:0F:DD/device_tracker'
    source_type: bluetooth_le

spotcast:
  sp_dc: !secret spotify_dc
  sp_key: !secret spotify_key

stream:

camera: !include cameras.yaml

mqtt:
  broker: nuc1.home
  username: !secret mqtt_username
  password: !secret mqtt_password

apcupsd:

python_script:

updater:

cloud:
