homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  unit_system: metric
  time_zone: !secret time_zone_home
  elevation: !secret elevation_home
  temperature_unit: C
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
     trusted_networks:
       - 10.0.0.0/24

lovelace:
  mode: yaml

config:

sun:

frontend:

mobile_app:

http:
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 2
  use_x_forwarded_for: True
  trusted_proxies:
    - 10.0.0.0/24
    - 127.0.0.1

tts:
  - platform: google_translate
    service_name: google_say

ssdp:

discovery:
  ignore:
    - samsung_tv

recorder:
  db_url: !secret recorder_db_url
  include:
    domains:
      - sensor
      - light
      - switch
      - binary_sensor

history:
  include:
    domains:
      - sensor
      - light
      - switch
      - binary_sensor

media_player:
  - platform: denonavr
    host: livingroom-receiver
    name: Livingroom Receiver
  - platform: webostv
    host: livingroom-tv
    name: Livingroom TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret livingroom_tv_mac_address

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include_dir_merge_list lights
switch: !include switches.yaml
cover: !include covers.yaml
sensor: !include_dir_merge_list sensors
zone: !secret zones
person: !secret persons

knx:

notify:
  - name: Pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: Livingroom TV
    platform: webostv
    host: livingroom-tv

verisure:
  username: !secret verisure_username
  password: !secret verisure_password
  hygrometers: false
  smartplugs: false
  thermometers: false
  mouse: false
  door_window: false
  locks: false

map:

tellstick:
  host: localhost
  port: [50800, 50801]
  signal_repetitions: 2

wake_on_lan:
