homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  unit_system: metric
  time_zone: !secret time_zone_home
  elevation: !secret elevation_home
  temperature_unit: C
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
     trusted_networks:
       - 10.0.0.0/24
  auth_mfa_modules:
   - type: totp
  customize: !include customize.yaml
  whitelist_external_dirs:
    - '/camera-files'
  external_url: !secret external_url

lovelace:
  mode: yaml
  resources:
    - url: /local/mini-graph-card-bundle.js
      type: module
    - url: /local/spotify-card.umd.js
      type: module
  dashboards:
    lovelace-tech:
      mode: yaml
      filename: dashboard-tech.yaml
      title: Teknik
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: false

config:

sun:

frontend:

mobile_app:

http:
  ip_ban_enabled: True
  login_attempts_threshold: 2
  use_x_forwarded_for: True
  trusted_proxies:
    - 10.0.0.8
    - 127.0.0.1

tts:
  - platform: google_translate
    service_name: google_say

ssdp:

discovery:

recorder:
  db_url: !secret recorder_db_url

history:

media_player:
  - platform: denonavr
    host: livingroom-receiver
    name: Livingroom Receiver

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include_dir_merge_list lights
switch: !include switches.yaml
cover: !include covers.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include binary_sensors.yaml
zone: !secret zones
person: !secret persons
knx: !include knx.yaml
input_text: !include input_text.yaml

notify:
  - name: Pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

verisure:
  username: !secret verisure_username
  password: !secret verisure_password
  hygrometers: false
  smartplugs: false
  thermometers: false
  mouse: false
  door_window: false
  locks: false

map:

tellstick:
  host: localhost
  port: [50800, 50801]
  signal_repetitions: 2

webostv:
  host: livingroom-tv
  name: Livingroom TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret livingroom_tv_mac_address

wake_on_lan:

asuswrt:
  host: router.asus.com
  username: admin
  ssh_key: /config/id_rsa
  sensors:
    - upload
    - download
    - upload_speed
    - download_speed

device_tracker:
  - platform: asuswrt
    host: router.asus.com
    username: admin
    ssh_key: /config/id_rsa
    protocol: ssh
    interval_seconds: 12
    consider_home: 300
    new_device_defaults:
      track_new_devices: true

speedtestdotnet:
  server_id: 26852 # Stockholm SUNET

spotcast:
  sp_dc: !secret spotify_dc
  sp_key: !secret spotify_key

stream:

camera: !include cameras.yaml

mqtt:
  broker: nuc1
  username: !secret mqtt_username
  password: !secret mqtt_password

apcupsd:

python_script:
