tunneling:
  host: '10.0.0.20'
  port: 3671

expose: !include knx/expose.yaml
light: !include_dir_merge_list knx/lights
switch: !include knx/switches.yaml
sensor: !include knx/sensors.yaml
cover: !include knx/covers.yaml
scene: !include knx/scenes.yaml
