- platform: tellstick
- platform: knx
  name: Coffee Maker
  address: '5/1/0'
  state_address: '5/4/0'
- platform: knx
  name: KNX Dummy Kids Room Plugs
  address: '1/1/46'
- platform: knx
  name: KNX Dummy Livingroom TV Bench Plug
  address: '1/1/2'
- platform: knx
  name: KNX Dummy Hallway Chimney Plug
  address: '1/1/32'
- platform: knx
  name: KNX Dummy Playroom Desk Plug
  address: '1/1/36'
- platform: knx
  name: Bedroom Cover Block
  address: '3/4/0'
- platform: knx
  name: Playroom Cover Block
  address: '3/4/1'
- platform: knx
  name: Livingroom Driveway Cover Block
  address: '3/4/2'
- platform: knx
  name: Livingroom Porch Cover Block
  address: '3/4/3'
