resources:
  - url: /local/mini-graph-card-bundle.js?v=0.8.2
    type: module
views:
  - path: default
    title: default
    icon: 'mdi:lightbulb'
    cards:
      - title: Vardagsrum
        type: entities
        entities:
          - entity: light.livingroom_windows
            name: Fönster
          - entity: light.livingroom_ceiling
            name: Tak
          - entity: switch.tv_bench
            name: TV-bänk
      - title: Kontor
        type: entities
        entities:
          - entity: light.office_window
            name: Fönster
          - entity: light.office_ceiling
            name: Tak
          - entity: switch.office_desk
            name: Skrivbord
          - entity: switch.office_reading_light
            name: Läslampa
      - type: vertical-stack
        cards:
          - type: entities
            title: Kök
            entities:
              - entity: light.kitchen_sink
                name: Diskho
              - entity: light.kitchen_spotlights
                name: Spotlights
              - entity: light.kitchen_window
                name: Fönster
              - entity: switch.coffee_maker
                name: Kaffebryggare
                icon: 'mdi:coffee-maker'
          - type: conditional
            conditions:
              - entity: switch.coffee_maker
                state: 'on'
            card:
              type: entities
              entities:
                - entity: sensor.coffee_maker_power_consumption
                  name: Kaffebryggare strömförbrukning
                  icon: 'mdi:flash'
      - title: Hall
        type: entities
        entities:
          - entity: light.hallway_shoe_cabinet
            name: Skoskåp
          - entity: light.hallway_spotlights
            name: Spotlights
          - entity: light.hallway_window
            name: Fönster
          - entity: switch.hallway_chimney
            name: Murstock
      - title: Matsal
        type: entities
        entities:
          - entity: light.dining_area_ceiling
            name: Matbord
          - entity: light.dining_area_vitrine_cabinet
            name: Vitrinskåp
          - entity: light.dining_area_wall_cabinet
            name: Väggskåp
      - title: Sovrum
        type: entities
        entities:
          - entity: light.bedroom_ceiling
            name: Tak
          - entity: light.bedroom_window
            name: Fönster
          - entity: light.bedroom_nightlights
            name: Nattduksbord
      - title: Badrum
        type: entities
        entities:
          - entity: light.bathroom_mirror
            name: Spegel
      - title: Barnrum
        type: entities
        entities:
          - entity: light.kids_room_ceiling
            name: Tak
          - entity: light.kids_room_window
            name: Fönster
          - entity: light.kids_room_light_boxes
            name: Kattvindsfack
          - entity: switch.kids_room_plug1
            name: Kanin
          - entity: switch.kids_room_plug2
            name: Ljusslinga
      - title: Utomhus
        type: entities
        entities:
          - entity: light.outdoor_garden
            name: Trädgård
          - entity: light.outdoor_cellar_entrance
            name: Källaringång
          - entity: light.outdoor_main_entrance
            name: Huvudingång
          - entity: light.outdoor_porch_entrance
            name: Altaningång
          - entity: light.outdoor_eave
            name: Takfot
          - entity: switch.conservatory
            name: Uterum
      - title: Toalett
        type: entities
        entities:
          - entity: light.toilet_ceiling
            name: Tak
          - entity: binary_sensor.toilet_occupancy
            name: Upptaget
  - path: central
    title: central
    icon: 'mdi:home'
    cards:
      - type: horizontal-stack
        cards:
          - entity: group.indoor_lights
            type: entity-button
            icon: 'mdi:lightbulb-off-outline'
            name: Släck allt
            tap_action:
              action: call-service
              service: homeassistant.turn_off
              service_data:
                entity_id: group.indoor_lights
          - entity: scene.evening_lights
            type: entity-button
            name: Kvällsbelysning
            icon: 'mdi:lightbulb-on-outline'
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.activate_evening_lights
      - title: Temperatur
        type: glance
        entities:
          - entity: sensor.outdoor_temperature
            name: Utomhus
          - entity: sensor.bathroom_temperature
            name: Badrum
          - entity: sensor.bedroom_temperature
            name: Sovrum
          - entity: sensor.kids_room_temperature
            name: Barnrum
          - entity: sensor.office_temperature
            name: Kontor
          - entity: sensor.toilet_temperature
            name: Toalett
          - entity: sensor.tool_shed_temperature
            name: Verktygsrum
      - title: Luftfuktighet
        type: glance
        entities:
          - entity: sensor.bathroom_humidity
            name: Badrum
          - entity: sensor.bedroom_humidity
            name: Sovrum
          - entity: sensor.kids_room_humidity
            name: Barnrum
          - entity: sensor.office_humidity
            name: Kontor
      - title: 'Rörelse'
        type: glance
        entities:
          - entity: binary_sensor.basement_porch_window_vibration
            name: Källarfönster 1
          - entity: binary_sensor.toilet_occupancy
            name: Toalett
      - title: 'Ljusstyrka'
        type: glance
        entities:
          - entity: sensor.outdoor_illuminance
            name: Utomhus
          - entity: sensor.toilet_illuminance
            name: Toalett
  - path: media
    title: media
    icon: 'mdi:play-circle'
    cards:
      - type: media-control
        entity: media_player.vardagsrum
      - type: media-control
        entity: media_player.hallway
      - type: media-control
        entity: media_player.sovrum
      - type: media-control
        entity: media_player.livingroom_receiver
      - type: media-control
        entity: media_player.livingroom_tv
      - type: media-control
        entity: media_player.spotify
  - path: climate
    title: climate
    icon: 'mdi:gauge'
    cards:
      - type: custom:mini-graph-card
        name: TEMPERATUR
        entities:
          - entity: sensor.kids_room_temperature
            name: BARNRUM
          - entity: sensor.office_temperature
            name: KONTOR
          - entity: sensor.bedroom_temperature
            name: SOVRUM
          - entity: sensor.bathroom_temperature
            name: BADRUM
          - entity: sensor.outdoor_temperature
            name: UTOMHUS
        hours_to_show: 24
        decimals: 1
        points_per_hour: 0.5
        hour24: true
      - type: custom:mini-graph-card
        name: BATTERINIVÅ
        entities:
          - entity: sensor.tool_shed_door_battery_level
            name: VERKTYGSRUM
          - entity: sensor.toilet_battery_level
            name: GÄSTTOALETT
          - entity: sensor.kids_room_battery_level
            name: BARNRUM
          - entity: sensor.office_battery_level
            name: KONTOR
          - entity: sensor.bedroom_battery_level
            name: SOVRUM
          - entity: sensor.bathroom_battery_level
            name: BADRUM
          - entity: sensor.basement_porch_window_vibration_battery_level
            name: KÄLLARFÖNSTER 1
        hours_to_show: 72
        decimals: 0
        points_per_hour: 0.2
        hour24: true
      - type: custom:mini-graph-card
        name: LUFTFUKTIGHET
        entities:
          - entity: sensor.kids_room_humidity
            name: BARNRUM
          - entity: sensor.office_humidity
            name: KONTOR
          - entity: sensor.bedroom_humidity
            name: SOVRUM
          - entity: sensor.bathroom_humidity
            name: BADRUM
        hours_to_show: 72
        decimals: 0
        points_per_hour: 0.5
        hour24: true
      - type: glance
        title: Vattenläckage
        entities:
          - entity: binary_sensor.kitchen_sink_water_leak
            name: Kök
  - path: security
    title: security
    icon: 'mdi:shield'
    cards:
      - type: alarm-panel
        entity: alarm_control_panel.hemma_alarm
        panel: true
        name: Larm
  - path: network
    title: network
    icon: 'mdi:network-router'
    cards:
      - type: entities
        title: Router
        show_header_toggle: false
        entities:
          - entity: sensor.asuswrt_download_speed
            name: Nedladdning
            icon: 'mdi:download'
          - entity: sensor.asuswrt_upload_speed
            name: Uppladdning
            icon: 'mdi:upload'
      - type: entities
        title: Speedtest
        show_header_toggle: false
        entities:
          - entity: sensor.speedtest_download
            name: Nedladdning
            icon: 'mdi:download'
          - entity: sensor.speedtest_upload
            name: Uppladdning
            icon: 'mdi:upload'
