- platform: knx
  name: Dining Area Ceiling
  address: '1/1/16'
  state_address: '1/4/16'
  brightness_address: '1/2/1'
  brightness_state_address: '1/3/0'
- platform: knx
  name: Dining Area Wall Cabinet
  address: '1/1/23'
  state_address: '1/4/23'
- platform: knx
  name: Dining Area Vitrine Cabinet
  address: '1/1/3'
  state_address: '1/4/3'
