- platform: knx
  name: Hallway Spotlights
  address: '1/1/28'
  state_address: '1/4/28'
  brightness_address: '1/2/22'
  brightness_state_address: '1/3/21'
- platform: knx
  name: Hallway Shoe Cabinet
  address: '1/1/29'
  state_address: '1/4/29'
- platform: knx
  name: Hallway Window
  address: '1/1/31'
  state_address: '1/4/31'
