- platform: rest
  name: Frigate Debug
  resource: http://nuc1:5002/debug/stats
  scan_interval: 5
  json_attributes:
    - driveway
    - front_door
    - porch
    - detectors
  value_template: 'OK'  
- platform: template
  sensors:
    driveway_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["driveway"]["process_fps"] }}'
      unit_of_measurement: 'FPS'
    porch_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["porch"]["process_fps"] }}'
      unit_of_measurement: 'FPS'
    front_door_fps: 
      value_template: '{{ states.sensor.frigate_debug.attributes["front_door"]["process_fps"] }}'
      unit_of_measurement: 'FPS'
    frigate_coral_inference:
      value_template: '{{ states.sensor.frigate_debug.attributes["detectors"]["coral"]["inference_speed"] }}' 
      unit_of_measurement: 'ms'
- platform: mqtt
  name: Driveway Event Start Last Id
  state_topic: 'frigate/driveway/events/start'
  value_template: '{{ value_json.id }}'
  json_attributes_topic: 'frigate/driveway/events/start'
- platform: mqtt
  name: Driveway Event End Last Id
  state_topic: 'frigate/driveway/events/end'
  value_template: '{{ value_json.id }}'
  json_attributes_topic: 'frigate/driveway/events/end'
- platform: mqtt
  name: Porch Event Start Last Id
  state_topic: 'frigate/porch/events/start'
  value_template: '{{ value_json.id }}'
  json_attributes_topic: 'frigate/porch/events/start'
- platform: mqtt
  name: Porch Event End Last Id
  state_topic: 'frigate/porch/events/end'
  value_template: '{{ value_json.id }}'
  json_attributes_topic: 'frigate/porch/events/end'
- platform: mqtt
  name: Front Door Event Start Last Id
  state_topic: 'frigate/front_door/events/start'
  value_template: '{{ value_json.id }}'
  json_attributes_topic: 'frigate/front_door/events/start'
- platform: mqtt
  name: Front Door Event End Last Id
  state_topic: 'frigate/front_door/events/end'
  value_template: '{{ value_json.id }}'
  json_attributes_topic: 'frigate/front_door/events/end'
