- platform: mqtt
  name: Galaxy S10e Basement Presence
  state_topic: 'monitor/basement/galaxy_s10e'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: Galaxy S10e Ground Floor Presence
  state_topic: 'monitor/ground_floor/galaxy_s10e'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: Mi Smart Band 5 Basement Presence
  state_topic: 'monitor/basement/DD:69:66:E7:0F:DD'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: Mi Smart Band 5 Ground Floor Presence
  state_topic: 'monitor/ground_floor/DD:69:66:E7:0F:DD'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
