- platform: knx
  name: Outdoor Temperature
  state_address: '4/0/0'
  type: temperature
- platform: knx
  name: Outdoor Wind Velocity
  state_address: '4/1/0'
  type: speed_ms
- platform: knx
  name: Outdoor Illuminance East
  state_address: '4/3/0'
  type: illuminance
- platform: knx
  name: Outdoor Illuminance South
  state_address: '4/3/1'
  type: illuminance
- platform: knx
  name: Outdoor Illuminance West
  state_address: '4/3/2'
  type: illuminance
- platform: knx
  name: Outdoor Illuminance
  state_address: '4/3/3'
  type: illuminance
