- platform: history_stats
  name: Livingroom TV Time
  entity_id: media_player.livingroom_tv
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Spotify Time
  entity_id: media_player.spotify
  state: 'playing'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
