- alias: 'Send notification on water leak'
  trigger:
    entity_id: binary_sensor.kitchen_sink_water_leak
    platform: state
    to: 'on'
  action:
    service: notify.pushover
    data:
      title: 'Water leak detected'
      message: 'A water leak was detected in the kitchen.'
      data:
        priority: 2
        expire: 3600
        retry: 30

- alias: 'Send notification on cellar window vibration and/or tilt'
  trigger:
    entity_id: binary_sensor.basement_porch_window_vibration
    platform: state
    to: 'on'
  action:
    service: notify.pushover
    data:
      title: 'Possible break-in detected'
      message: 'The vibration sensor in the basement has been picking up vibrations.'
      data:
        priority: 2
        expire: 3600
        retry: 30

- alias: 'Send notification on tool shed door opened/closed if alarm is activated'
  trigger:
    entity_id: binary_sensor.tool_shed_door_open
    platform: state
  condition:
    condition: template
    value_template: '{{ states.alarm_control_panel.hemma_alarm.state != "disarmed" }}'
  action:
    service: notify.pushover
    data:
      title: 'Possible break-in detected'
      message: 'The tool shed door was opened or closed while house was armed.'
