- alias: 'Send notification on water leak'
  trigger:
    entity_id: binary_sensor.kitchen_sink_water_leak
    platform: state
    to: 'on'
  action:
    service: notify.mobile_app_sm_g965f
    data:
      title: 'Water leak detected'
      message: 'A water leak was detected in the kitchen.'

- alias: 'Send notification on cellar window vibration and/or tilt'
  trigger:
    entity_id: binary_sensor.basement_porch_window_presence
    platform: state
    to: 'on'
  action:
    service: notify.mobile_app_sm_g965f
    data:
      title: 'Possible break-in detected'
      message: 'The vibration sensor in the basement has been picking up vibrations.'

- alias: 'Simple basement burglar detection'
  trigger:
    entity_id: binary_sensor.basement_hallway_presence
    platform: state
    to: 'on'
  condition:
    condition: template
    value_template: "{{ states.alarm_control_panel.hemma_alarm.state != 'disarmed' }}"
  action:
    - service: input_text.set_value
      entity_id: input_text.tool_shed_door_last_state
      data_template:
        value: "{{ states('binary_sensor.tool_shed_door_open') }}"
    - wait_template: "{{ not is_state('binary_sensor.tool_shed_door_open', states('input_text.tool_shed_door_last_state')) }}"
      timeout: '00:05:00'
      continue_on_timeout: 'false'
    - service: notify.mobile_app_sm_g965f
      data:
        title: 'Possible break-in detected'
        message: 'The basement sensors reported activity while house was armed.'

- alias: 'Turn ground floor lights on in case the alarm goes off'
  trigger:
    entity_id: switch.smartplug1_on_off
    platform: state
    from: 'unavailable'
  condition:
    - condition: template
      value_template: "{{ states.alarm_control_panel.hemma_alarm.state != 'disarmed' }}"
    - condition: numeric_state
      entity_id: sensor.outdoor_illuminance
      below: 300
  action:
    - service: notify.mobile_app_sm_g965f
      data:
        title: 'Alarm went off'
        message: 'Turning the ground floor lights on in an attempt to scare the burglars away.'
    - service: homeassistant.turn_on
      entity_id: group.ground_floor_lights
