- alias: 'Turn on sleep-friendly bedroom lights'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: bedroom_switch
        event: 1002 # Single click
    - platform: event
      event_type: deconz_event
      event_data:
        id: bedroom_switch_2
        event: 1002 # Single click
  condition:
    - condition: time
      after: '20:00:00'
      before: '02:00:00'
  action:
    - service: homeassistant.toggle
      entity_id: light.bedroom_window
