- alias: 'Notify/Trigger alarm on camera motion events when armed away'
  mode: single # to stop this automation from spamming
  trigger:
    - platform: mqtt
      topic: frigate/events
  variables:
    trigger_alarm_for_cameras:
      - livingroom
    camera_snapshot_url: '/api/frigate/notifications/{{ trigger.payload_json["after"]["id"] }}/thumbnail.jpg'
    notification_title: "{{ state_attr('alarm_control_panel.home_alarm', 'friendly_name') }}"
    notification_message: 'A {{ trigger.payload_json["after"]["label"] }} was detected on camera {{ trigger.payload_json["after"]["camera"] }}'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
    - condition: template
      value_template: '{{ trigger.payload_json["after"]["camera"] != "driveway"
        or (trigger.payload_json["after"]["label"] == "car"
          and "driveway" not in trigger.payload_json["after"]["current_zones"]
          and "driveway" in trigger.payload_json["after"]["entered_zones"]) }}'
  action:
    - service: script.alarm_notification_with_image
      data:
        title: '{{ notification_title }}'
        message: '{{ notification_message }}'
        image: '{{ camera_snapshot_url }}'
    - condition: template
      value_template: '{{ trigger.payload_json["after"]["camera"] in trigger_alarm_for_cameras }}'
    - service: alarm_control_panel.alarm_trigger
      target:
        entity_id: alarm_control_panel.home_alarm
    - delay: 30

- alias: 'Notify on camera motion events when armed home'
  mode: single # to stop this automation from spamming
  trigger:
    - platform: mqtt
      topic: frigate/events
  variables:
    active_cameras:
      - driveway
      - front_door
      - porch
    camera_snapshot_url: '/api/frigate/notifications/{{ trigger.payload_json["after"]["id"] }}/thumbnail.jpg'
    notification_title: "{{ state_attr('alarm_control_panel.home_alarm', 'friendly_name') }}"
    notification_message: 'A {{ trigger.payload_json["after"]["label"] }} was detected on camera {{ trigger.payload_json["after"]["camera"] }}'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_home
    - condition: template
      value_template: '{{ trigger.payload_json["after"]["camera"] in active_cameras }}'
    - condition: template
      value_template: '{{ trigger.payload_json["after"]["camera"] != "driveway"
        or (trigger.payload_json["after"]["label"] == "car"
          and "driveway" not in trigger.payload_json["after"]["current_zones"]
          and "driveway" in trigger.payload_json["after"]["entered_zones"]) }}'
  action:
    - service: script.alarm_notification_with_image
      data:
        title: '{{ notification_title }}'
        message: '{{ notification_message }}'
        image: '{{ camera_snapshot_url }}'
    - delay: 30

- alias: 'Flash outside lights on porch camera motion events when armed home'
  mode: single # to stop this automation from spamming
  trigger:
    - platform: mqtt
      topic: frigate/events
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_home
    - condition: template
      value_template: '{{ trigger.payload_json["after"]["camera"] == "porch" }}'
  action:
    - service: script.alarm_toggle_outside_porch_lights
    - delay: 30
