- alias: 'Turn on toilet ceiling lights on motion detected'
  trigger:
    entity_id: binary_sensor.toilet_presence
    platform: state
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.turn_toilet_lights_on_with_conditional_delay

- alias: 'Turn off toilet ceiling lights when presence expires'
  trigger:
    entity_id: binary_sensor.toilet_presence
    platform: state
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: light.toilet_ceiling

- alias: 'Reset toilet lights automation 20 min after it has been turned off'
  trigger:
    entity_id: automation.turn_off_toilet_ceiling_lights_when_presence_expires
    platform: state
    to: 'off'
  action:
    - delay: '00:20:00'
    - service: homeassistant.turn_on
      entity_id: automation.turn_off_toilet_ceiling_lights_when_presence_expires

- alias: 'Turn off toilet lights when the automation is reset and room is empty'
  trigger:
    entity_id: automation.turn_off_toilet_ceiling_lights_when_presence_expires
    platform: state
    to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.toilet_presence
    state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: light.toilet_ceiling

- alias: 'Turn on evening lights at dusk'
  trigger:
    platform: numeric_state
    entity_id: sensor.outdoor_illuminance
    below: 500
    for:
      minutes: 5
  condition:
    condition: time
    after: '12:00:00'
    before: '22:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: script.activate_evening_lights

- alias: 'Send notifications on low battery for sensors'
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.basement_porch_window_vibration_battery_level
      - sensor.basement_hallway_battery_level
      - sensor.bathroom_battery_level
      - sensor.bedroom_battery_level
      - sensor.kids_room_battery_level
      - sensor.kitchen_sink_water_leak_battery_level
      - sensor.office_battery_level
      - sensor.tool_shed_door_battery_level
      - sensor.toilet_battery_level
      - sensor.attic_battery_level
      - sensor.laundry_room_battery_level
    below: 20
  action:
    service: notify.mobile_app_sm_g965f
    data_template:
      title: 'Batteries are running low'
      message: '{{ trigger.to_state.attributes.friendly_name }} only has {{ trigger.to_state.state }}% of juice left.'

- alias: 'Turn off indoor lights when alarm is armed home'
  trigger:
    platform: state
    entity_id: alarm_control_panel.hemma_alarm
    to: 'armed_home'
  action:
    service: homeassistant.turn_off
    entity_id: group.indoor_lights

- alias: "Turn off indoor lights when alarm is armed away unless it's dark outside"
  trigger:
    platform: state
    entity_id: alarm_control_panel.hemma_alarm
    to: 'armed_away'
  condition:
    condition: numeric_state
    entity_id: sensor.outdoor_illuminance
    above: 500
  action:
    service: homeassistant.turn_off
    entity_id: group.indoor_lights

- alias: 'Activate morning scene for workday mornings'
  trigger:
    platform: state
    entity_id: alarm_control_panel.hemma_alarm
    to: 'disarmed'
  condition:
    - condition: template
      value_template: "{{ state_attr('alarm_control_panel.hemma_alarm', 'changed_by') == state_attr('person.person1', 'friendly_name') }}"
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: time
      after: '05:00:00'
      before: '06:10:00'
  action:
    - service: homeassistant.turn_on
      entity_id: scene.workday_morning

- alias: 'Turn on dimmed bedroom lights'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_switch
      event: 1002
  action:
    service: homeassistant.toggle
    entity_id: light.bedroom_window
