- alias: 'Turn on evening lights at dusk'
  trigger:
    - platform: numeric_state
      entity_id: sensor.outdoor_illuminance
      below: 500
      for:
        minutes: 5
  condition:
    - condition: time
      after: '12:00:00'
      before: '22:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: script.activate_evening_lights

- alias: 'Send notifications on low battery for sensors'
  trigger:
    - platform: event
      event_type: state_changed
      event_data:
        domain: sensor
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.entity_id.endswith('_battery_level') }}"
    - condition: template
      value_template: "{{ trigger.event.data.new_state.state | int < 20 }}"
  action:
    - service: notify.mobile_app_person_1_s10e
      data:
        title: 'Batteries are running low'
        message: 'Sensor {{ state_attr(trigger.event.data.entity_id, "name") }} only has {{ trigger.event.data.new_state.state }}{{ state_attr(trigger.event.data.entity_id, "unit_of_measurement") }} of juice left.'

- alias: 'Activate morning scene for workday mornings'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: disarmed
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.context.user_id == state_attr('person.person1', 'user_id') }}"
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: time
      after: '05:00:00'
      before: '06:10:00'
  action:
    - service: homeassistant.turn_on
      entity_id: scene.workday_morning

- alias: 'Turn off the kids nightlights when the day starts'
  trigger:
    - platform: numeric_state
      entity_id: sensor.outdoor_illuminance
      above: 500
      for:
        minutes: 10
  action:
    - service: homeassistant.turn_off
      entity_id: light.light_strip_1

- alias: 'Turn off bedtime started entity at midnight'
  trigger:
    - platform: time
      at: '00:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.kids_bedtime_started
