- alias: 'Turn on toilet ceiling lights on motion detected'
  trigger:
    entity_id: binary_sensor.toilet_presence
    platform: state
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.turn_toilet_lights_on_with_conditional_delay

- alias: 'Turn off toilet ceiling lights when presence expires'
  trigger:
    entity_id: binary_sensor.toilet_presence
    platform: state
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: light.toilet_ceiling

- alias: 'Turn on evening lights at dusk'
  trigger:
    platform: numeric_state
    entity_id: sensor.outdoor_illuminance
    below: 300
    for:
      minutes: 10
  condition:
    condition: time
    after: '12:00:00'
    before: '22:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: script.activate_evening_lights

- alias: 'Send notifications on low battery for sensors'
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.basement_porch_window_vibration_battery_level
      - sensor.basement_hallway_battery_level
      - sensor.bathroom_battery_level
      - sensor.bedroom_battery_level
      - sensor.kids_room_battery_level
      - sensor.kitchen_sink_water_leak_battery_level
      - sensor.office_battery_level
      - sensor.tool_shed_door_battery_level
      - sensor.toilet_battery_level
      - sensor.attic_battery_level
      - sensor.laundry_room_battery_level
    below: 20
  action:
    service: notify.pushover
    data_template:
      title: 'Batteries are running low'
      message: '{{ trigger.to_state.attributes.friendly_name }} only has {{ trigger.to_state.state }}% of juice left.'

- alias: 'Turn off indoor lights when alarm is armed'
  trigger:
    platform: state
    entity_id: alarm_control_panel.hemma_alarm
    to: 'armed_home'
  action:
    service: homeassistant.turn_off
    entity_id: group.indoor_lights

- alias: 'Activate morning scene for workday mornings'
  trigger:
    platform: state
    entity_id: alarm_control_panel.hemma_alarm
    to: 'disarmed'
  condition:
    - condition: template
      value_template: "{{ state_attr('alarm_control_panel.hemma_alarm', 'changed_by') == state_attr('person.person1', 'friendly_name') }}"
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: time
      after: '05:20:00'
      before: '06:10:00'
  action:
    - service: homeassistant.turn_on
      entity_id: scene.workday_morning
