- alias: 'Turn on toilet ceiling lights on motion detected'
  trigger:
    - entity_id: binary_sensor.toilet_occupancy
      platform: state
      to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.toilet_ceiling

- alias: 'Turn off toilet ceiling lights when occupancy expires'
  trigger:
    - entity_id: binary_sensor.toilet_occupancy
      platform: state
      to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: light.toilet_ceiling

- alias: 'Turn on evening lights at dusk'
  trigger:
    platform: numeric_state
    entity_id: sensor.outdoor_illuminance
    below: 250
    for:
      minutes: 10
  condition:
    - condition: time
      after: '14:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.evening_lights
    - service: homeassistant.turn_on
      entity_id:
        - switch.smartplug1_on_off
        - switch.office_desktop
        - switch.hallway_ff
        - switch.tv_bench

- alias: 'Send notifications on low battery for sensors'
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.basement_porch_window_vibration_battery_level
      - sensor.bathroom_battery_level
      - sensor.bedroom_battery_level
      - sensor.kids_room_battery_level
      - sensor.kitchen_sink_water_leak_battery_level
      - sensor.office_battery_level
      - sensor.tool_shed_door_battery_level
      - sensor.toilet_battery_level
    below: 20
  action:
    service: notify.pushover
    data:
      title: 'Batteries are running low'
      message: '{{ trigger.to_state.attributes.friendly_name }} only has {{ trigger.to_state.state }}% of power left.'

- alias: 'Toggle TV bench plug when KNX panel button is pressed'
  trigger:
    - entity_id: switch.knx_dummy_livingroom_tv_bench_plug
      platform: state
  action:
    service: homeassistant.toggle
    entity_id: switch.tv_bench

- alias: 'Toggle hallway chimney plug when KNX panel button is pressed'
  trigger:
    - entity_id: switch.knx_dummy_hallway_chimney_plug
      platform: state
  action:
    service: homeassistant.toggle
    entity_id: switch.hallway_chimney

- alias: 'Toggle office desk plug when KNX panel button is pressed'
  trigger:
    - entity_id: switch.knx_dummy_office_desk_plug
      platform: state
  action:
    service: homeassistant.toggle
    entity_id: switch.office_desk

- alias: 'Toggle kids room corner plug when KNX panel button is pressed'
  trigger:
    - entity_id: switch.knx_dummy_kids_room_corner_plug
      platform: state
  action:
    service: homeassistant.toggle
    entity_id: switch.kids_room_corner
