- alias: 'Turn on toilet ceiling lights on motion detected'
  trigger:
    entity_id: binary_sensor.toilet_occupancy
    platform: state
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.toilet_ceiling

- alias: 'Turn off toilet ceiling lights when occupancy expires'
  trigger:
    entity_id: binary_sensor.toilet_occupancy
    platform: state
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: light.toilet_ceiling

- alias: 'Turn on evening lights at dusk'
  trigger:
    platform: numeric_state
    entity_id: sensor.outdoor_illuminance
    below: 280
    for:
      minutes: 10
  condition:
    condition: time
    after: '13:00:00'
    before: '19:00:00'
  action:
    service: script.turn_on
    entity_id: script.activate_evening_lights

- alias: "Turn on evening lights that won't wake the kids up"
  trigger:
    platform: numeric_state
    entity_id: sensor.outdoor_illuminance
    below: 280
    for:
      minutes: 10
  condition:
    condition: time
    after: '19:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: group.kids_asleep_evening_lights

- alias: 'Send notifications on low battery for sensors'
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.basement_porch_window_vibration_battery_level
      - sensor.bathroom_battery_level
      - sensor.bedroom_battery_level
      - sensor.kids_room_battery_level
      - sensor.kitchen_sink_water_leak_battery_level
      - sensor.office_battery_level
      - sensor.tool_shed_door_battery_level
      - sensor.toilet_battery_level
    below: 20
  action:
    service: notify.pushover
    data_template:
      title: 'Batteries are running low'
      message: '{{ trigger.to_state.attributes.friendly_name }} only has {{ trigger.to_state.state }}% of power left.'
