- alias: 'Toggle TV bench plug when KNX panel button is pressed'
  trigger:
    - entity_id: switch.knx_dummy_livingroom_tv_bench_plug
      platform: state
  action:
    service: homeassistant.toggle
    entity_id: switch.tv_bench

- alias: 'Toggle hallway chimney plug when KNX panel button is pressed'
  trigger:
    - entity_id: switch.knx_dummy_hallway_chimney_plug
      platform: state
  action:
    service: homeassistant.toggle
    entity_id: switch.hallway_chimney

- alias: 'Toggle office desk plug when KNX panel button is pressed'
  trigger:
    - entity_id: switch.knx_dummy_office_desk_plug
      platform: state
  action:
    service: homeassistant.toggle
    entity_id: switch.office_desk

- alias: 'Toggle kids room plugs when KNX panel button is pressed'
  trigger:
    - entity_id: switch.knx_dummy_kids_room_plugs
      platform: state
  action:
    service: homeassistant.toggle
    entity_id:
      - switch.kids_room_plug1
      - switch.kids_room_plug2
