- alias: 'Toggle kids room plugs when KNX panel button is pressed'
  trigger:
    - entity_id: switch.knx_dummy_kids_room_plugs
      platform: state
  action:
    service: homeassistant.toggle
    entity_id:
      - switch.smart_plug_1
      - switch.smart_plug_2

- alias: 'Turn on bathroom mirror bulbs when KNX panel button is pressed'
  trigger:
    - entity_id: switch.knx_dummy_bathroom_mirror_bulbs
      platform: state
      to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.bathroom_mirrors_manually_turned_off
    - service: homeassistant.turn_on
      entity_id: input_boolean.bathroom_mirrors_manually_turned_on
    - service: light.turn_on
      entity_id: light.bathroom_mirror_1
      data:
        brightness: "{{ states('input_number.bathroom_mirror_1_brightness') | int }}"
        kelvin: "{{ states('input_number.bathroom_mirror_kelvin') | int }}"
    - service: light.turn_on
      entity_id: light.bathroom_mirror_2
      data:
        brightness: "{{ states('input_number.bathroom_mirror_2_brightness') | int }}"
        kelvin: "{{ states('input_number.bathroom_mirror_kelvin') | int }}"

- alias: 'Turn off bathroom mirror bulbs when KNX panel button is pressed'
  trigger:
    - entity_id: switch.knx_dummy_bathroom_mirror_bulbs
      platform: state
      to: 'off'
  condition:
    - condition: state
      entity_id: timer.bathroom_nightlights
      state: idle
  action:
    - service: light.turn_off
      entity_id:
        - light.bathroom_mirror_1
        - light.bathroom_mirror_2
    - service: homeassistant.turn_on
      entity_id: input_boolean.bathroom_mirrors_manually_turned_off
    - service: homeassistant.turn_off
      entity_id: input_boolean.bathroom_mirrors_manually_turned_on
