- alias: "Turn on the office heater to make sure it's warm when the workday starts"
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    #- entity_id: binary_sensor.office_presence
    #  platform: state
    #  to: 'on'
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.office_temperature
      below: 21
  action:
    - service: homeassistant.turn_on
      entity_id: switch.office_heater
    - service: notify.mobile_app_sm_g970f
      data:
        title: 'Office heater started'
        message: "Making the office warm and comfy until your arrival."

- alias: 'Turn off the office heater when the temperature is good enough'
  trigger:
    entity_id: sensor.office_temperature
    platform: numeric_state
    above: 22
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: switch.laundry_dryer
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.office_heater

- alias: 'Send a reminder to close the office window if the room has been unoccupied for some time'
  trigger:
    entity_id: binary_sensor.office_presence
    platform: state
    to: 'off'
    for:
      hours: 2
  condition:
    condition: state
    entity_id: binary_sensor.office_window
    state: 'on'
  action:
    - service: notify.mobile_app_sm_g970f
      data:
        title: 'Office window currently open'
        message: "Did you forget to close the office window?"
