- alias: 'Turn on outdoor lights at dawn'
  trigger:
    platform: numeric_state
    entity_id: sensor.outdoor_illuminance
    below: 30
    for:
      minutes: 10
  condition:
    - condition: time
      after: '14:00:00'
  action:
    service: homeassistant.turn_on
    entity_id:
      - group.main_outdoor_lights
      - group.complementary_outdoor_lights

- alias: 'Turn off main outdoor lights at dusk'
  trigger:
    platform: numeric_state
    entity_id: sensor.outdoor_illuminance
    above: 30
    for:
      minutes: 10
  action:
    service: homeassistant.turn_off
    entity_id: group.main_outdoor_lights

- alias: 'Turn off complementary outdoor lights at a specific time'
  trigger:
    platform: time
    at: '23:13:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.complementary_outdoor_lights
