- alias: 'Turn on outdoor lights at dusk'
  trigger:
    - platform: numeric_state
      entity_id: sensor.outdoor_illuminance
      below: 200
      for:
        minutes: 5
  condition:
    - condition: time
      after: '12:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id:
        - group.main_outdoor_lights
        - group.complementary_outdoor_lights

- alias: 'Turn off main outdoor lights at dawn'
  trigger:
    - platform: numeric_state
      entity_id: sensor.outdoor_illuminance
      above: 230
      for:
        minutes: 5
  condition:
    - condition: time
      after: '00:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: group.main_outdoor_lights

- alias: 'Turn off complementary outdoor lights at a random minute between 11pm and 12pm'
  trigger:
    - platform: time
      at: '23:00:00'
  action:
    - delay: "{{ range(0, 3600) | random | int }}"
    - service: homeassistant.turn_off
      entity_id: group.complementary_outdoor_lights
