- alias: 'Turn off all ground floor lights when Person 1 is leaving home in the morning'
  trigger:
    platform: state
    entity_id: group.person1_tracker
    from: 'home'
    to: 'not_home'
  condition:
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: time
      after: '05:25:00'
      before: '06:25:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.ground_floor_lights
