- alias: 'Turn off all ground floor lights when Person 1 is leaving home in the morning'
  trigger:
    platform: state
    entity_id: person.person1
    from: 'home'
  condition:
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: time
      after: '05:25:00'
      before: '06:25:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.ground_floor_lights

- alias: 'Arm away when everyone is away from home for more than 5 minutes'
  trigger:
    - platform: state
      entity_id: binary_sensor.people_home
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: disarmed
    - condition: time
      after: '08:00:00'
      before: '23:00:00'
  action:
    - service: notify.all_apps
      data:
        title: "{{ state_attr('alarm_control_panel.home_alarm', 'friendly_name') }}"
        message: "It seems you forgot to arm the alarm system when you left home. I'll do it for you in 2 minutes."
        data:
          actions:
            - action: ARM_CONFIRM
              title: Confirm
            - action: ARM_CANCEL
              title: Cancel
    - service: timer.start
      entity_id: timer.alarm_automatic_arm

- alias: 'Arm the alarm directly instead of waiting for timer'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: ARM_CONFIRM
  action:
    - service: timer.finish
      entity_id: timer.alarm_automatic_arm

- alias: 'Cancel the alarm timer'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: ARM_CANCEL
  action:
    - service: timer.cancel
      entity_id: timer.alarm_automatic_arm

- alias: 'Arm away when timer finishes'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.alarm_automatic_arm
  action:
    service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.home_alarm
    data:
      code: !secret home_alarm_code
